export enum AppRoutes {
    Brands = 'brands',
    Add = 'add',
    List = 'list',
    Tracking = 'tracking',
    Capping = 'capping',
    Update = 'update',
    View = 'view',
    Reports = 'reports',
    ReportList = 'reports-list',
    ConversionLogs = 'conversions-logs',
    Category = 'category',
    Product = 'product',
    login = 'login',
    Dashboard = 'dashboard',
    Store = "store",
    Brand = "brand",
    Coupan = "coupan",
    Banner = "banner",
    Deals = "deals"
  }